# Generated by Django 5.0.4 on 2024-06-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_category_options_item_stock_itemrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
    ]
