# Generated by Django 5.0.4 on 2024-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_number',
            field=models.IntegerField(default=0),
        ),
    ]
