# Generated by Django 5.0.4 on 2024-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_allow_banner_profile_banner_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_number',
            field=models.IntegerField(default=1),
        ),
    ]
